### PR TITLE
#1036 #1035 applicationData fix and additional migration

### LINKED ISSUE #1035: Add "application_id" column to "action_queue" table
Won't make any difference to functionality, but it'll make it easier for us to find and diagnose action error for specific applications.

Should only take under an hour.

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #1035 and #1036

The migration to add "application_id" column is a bit gnarly, but it's worth it to have this in there -- it also means actions and triggers that no longer have an associated application will automatically get deleted.

### To test

**For #1035**:
- Load various snapshots, and check that after loading/migration, the `trigger_queue` and `action_queue` tables have a populated `application_id` field.
- Try doing a few things that cause triggers (start/submit/assign etc) and check that the actions behave as normal and that they get `application_id` stored in the action and trigger queues

**For #1036**:
- Find a submitted application, then remove the applicant from the organisation they applied on behalf of. Then run the `getApplicationData` endpoint -- you should still get the correct organisation (id and name) data for the application (if you do the same thing on `develop`, the orgId and orgName fields will be `null`)

### CODE REVIEW

File: database/migration/migrateData.ts [hunk 1]
```diff
@@ -723,6 +723,37 @@ const migrateData = async () => {
...
+    console.log(' - Update FK reference to trigger_queue in action_queue')
+    await DB.changeSchema(`
+      ALTER TABLE action_queue DROP CONSTRAINT IF EXISTS   
+        action_queue_trigger_event_fkey; 
+      ALTER TABLE action_queue ADD CONSTRAINT action_queue_trigger_event_fkey
+        FOREIGN KEY (trigger_event) REFERENCES trigger_queue (id) ON DELETE CASCADE;
+    `)
+
+    console.log(' - Add application_id column to trigger_queue & action_queue')
+    if (!(await DB.checkColumnExists('trigger_queue', 'application_id'))) {
```
Comment (CarlosNZ) [inline database/migration/migrateData.ts:737]: Added this additional check (in addition to the version check), because this is quite a slow process, so we want to make sure it only ever runs once.

File: src/components/postgresConnect.ts [hunk 2]
```diff
@@ -594,13 +594,19 @@ class PostgresDB {
...
+    status,
+  }: TriggerQueueUpdatePayload): Promise<boolean> => {
+    const text = `UPDATE trigger_queue SET status = $1${
+      application_id ? ', application_id = $3' : ''
+    } WHERE id = $2`
+    const values = [status, id]
+    if (application_id) values.push(application_id)
+
+    try {
+      await this.query({ text, values })
```
Comment (fergie-nz) [inline src/components/postgresConnect.ts:609]: I don't quite understand the mechanism of this code, but it is working well - I'll take some time later to properly wrap my head around it.

**Review by fergie-nz — APPROVED** [review]
Looks great and working well

File: src/components/postgresConnect.ts (hunk 2 above)
Comment (CarlosNZ) [reply src/components/postgresConnect.ts:609]: This bit is a bit messy, but it's just building a conditional SQL query, because the `application_id` may or may not be present, so the query string has to change accordingly. You'll see other examples of this around such as when the `orgId` might be present or not.
